version: 2

project_name: openclaw-trace

builds:
  - id: openclaw-trace
    main: ./cmd/openclaw-trace
    binary: openclaw-trace
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath

archives:
  - formats: [tar.gz]
    files:
      - README.md

checksum:
  name_template: checksums.txt
